Target path should not with lines in pool xml
The xml for define and create pool is with line switch in target
path.

For aa.xml:
<pool type="netfs">
  <name>netfs_pool</name>
  <source>
    <host name="192.168.0.121"/>
    <dir path="/dir"/>
    <format type="nfs"/>
  </source>
  <target>
    <path>
      /tmp/netfs
    </path>
  </target>
</pool>

virsh pool-create aa.xml
error: Failed to create pool from aa.xml
error: cannot open path '
        /tmp/netfs
      ': No such file or directory

Signed-off-by: Wayne Sun <gsun@redhat.com>